FROM openjdk:8-jdk-alpine
MAINTAINER baeldung.com
COPY target/spring-rest-hello-world-1.0.jar spring-rest-hello-world-1.0.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","spring-rest-hello-world-1.0.jar"] 
